// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int count = Integer.parseInt(args[0]); // the number of times w4e will run the loop
		double curent_number = -1; 
		double greater_than_0_5 = 0;
		double less_or_equal_than_0_5 = 0;
		
		// running the Math.random function in a loop N times.
		while (count != 0){
			curent_number = Math.random();
			// checking if the random number is grater or less_equal than 0.5 and adding to the count.
			if (curent_number > 0.5){
				greater_than_0_5++;
			}
			else {
				less_or_equal_than_0_5++;
			}
			count--;
		}
		
		// if there were more less_equal than 0.5 numbers
		if (less_or_equal_than_0_5 == 0){
			System.out.println("> 0.5: " + greater_than_0_5 + "\n<= 0.5: " + less_or_equal_than_0_5);
		} 
		// else calculate the ratio of greater than 0.5 to less or equal than 0.5.
		else {
			double ratio = greater_than_0_5/less_or_equal_than_0_5;
			System.out.println("> 0.5: " + (int) greater_than_0_5 + "\n<= 0.5: " + (int) less_or_equal_than_0_5 +
								"\nRatio: " + ratio);

		}
	}
}
